{
    parserClass = "io.github.asmflow.assembly.armv7.parser.ARMv7Parser"
    parserUtilClass = "io.github.asmflow.assembly.armv7.parser.ARMv7ParserUtil"

    extends = "com.intellij.extapi.psi.ASTWrapperPsiElement"

    elementTypeClass = "io.github.asmflow.assembly.armv7.psi.ARMv7ElementType"
    elementTypeHolderClass = "io.github.asmflow.assembly.armv7.psi.ARMv7TokenTypes"

    psiClassPrefix = "ARMv7"
    psiPackage = "io.github.asmflow.assembly.armv7.psi"
    psiImplClassSuffix = "Impl"
    psiImplPackage = "io.github.asmflow.assembly.armv7.psi.impl"

    tokenTypeClass = "io.github.asmflow.assembly.armv7.psi.ARMv7TokenType"

    classHeader = "header.txt"

    tokens = [
        COMMENT = "comment"
        IDENTIFIER = "identifier"
        LINE_FEED = "lf"
        STRING = "string"

        // numbers
        BINARY_NUMBER = "binary number"
        DECIMAL_NUMBER = "decimal number"
        HEXADECIMAL_NUMBER = "hexadecimal number"
        OCTAL_NUMBER = "octal number"

        // registers
        REG = "register"

        // symbols
        BANG = "!"
        COMMA = ","
        COLON = ":"
        DOT = "."
        LBRACKET = "["
        MINUS = "-"
        PLUS = "+"
        POUND = "#"
        RBRACKET = "]"
    ]
}

File ::= Item*
private Item ::= (LabelWithColon | Instruction | Directive) LINE_FEED | LINE_FEED

Register ::= REG {
  mixin = "io.github.asmflow.assembly.armv7.psi.impl.ARMv7RegisterMixinImpl"
  implements = "io.github.asmflow.assembly.armv7.psi.ARMv7RegisterMixin"
}

Directive ::= DOT DirectiveName DirectiveParameters? {
  pin = 2
}
DirectiveName ::= IDENTIFIER
DirectiveParameters ::= DirectiveParameter (COMMA DirectiveParameter)*
DirectiveParameter ::= Label | STRING

Instruction ::= Mnemonic Operands? {
  pin = 1
  mixin = "io.github.asmflow.assembly.armv7.psi.impl.ARMv7InstructionMixinImpl"
  implements = "io.github.asmflow.assembly.armv7.psi.ARMv7InstructionMixin"
}
Operands ::= Operand (COMMA Operand)*
Operand ::= RegisterOperand | Label | Number {
  mixin = "io.github.asmflow.assembly.armv7.psi.impl.ARMv7OperandMixinImpl"
  implements = "io.github.asmflow.assembly.armv7.psi.ARMv7OperandMixin"
}

private RegisterOperand ::= Postindexed
  | Preindexed
  | RegisterWithShift

Postindexed ::= LBRACKET Register RBRACKET COMMA FlexibleOffset
Preindexed ::= LBRACKET Register (COMMA FlexibleOffset)? RBRACKET BANG?
FlexibleOffset ::= Number | Sign? RegisterWithShift

RegisterWithShift ::= Register (COMMA Shift)?
Shift ::= ShiftType (Number | Register)

Mnemonic ::= IDENTIFIER

ShiftType ::= IDENTIFIER

LabelWithColon ::= Label COLON
Label ::= IDENTIFIER

Sign ::= PLUS | MINUS {
  mixin = "io.github.asmflow.assembly.armv7.psi.impl.ARMv7SignMixinImpl"
  implements = "io.github.asmflow.assembly.armv7.psi.ARMv7SignMixin"
}
Number ::= POUND Sign? NumberLiteral {
  mixin = "io.github.asmflow.assembly.armv7.psi.impl.ARMv7NumberOperandMixinImpl"
  implements = "io.github.asmflow.assembly.armv7.psi.ARMv7OperandMixin"
}
private NumberLiteral ::= !<<afterWhitespace>> (BinaryLiteral | DecimalLiteral | HexadecimalLiteral | OctalLiteral)

BinaryLiteral ::= BINARY_NUMBER {
  mixin = "io.github.asmflow.assembly.armv7.psi.impl.ARMv7BinaryNumberMixinImpl"
  implements = "io.github.asmflow.assembly.armv7.psi.ARMv7NumberMixin"
}
DecimalLiteral ::= DECIMAL_NUMBER {
  mixin = "io.github.asmflow.assembly.armv7.psi.impl.ARMv7DecimalNumberMixinImpl"
  implements = "io.github.asmflow.assembly.armv7.psi.ARMv7NumberMixin"
}
HexadecimalLiteral ::= HEXADECIMAL_NUMBER {
  mixin = "io.github.asmflow.assembly.armv7.psi.impl.ARMv7HexadecimalNumberMixinImpl"
  implements = "io.github.asmflow.assembly.armv7.psi.ARMv7NumberMixin"
}
OctalLiteral ::= OCTAL_NUMBER {
  mixin = "io.github.asmflow.assembly.armv7.psi.impl.ARMv7OctalNumberMixinImpl"
  implements = "io.github.asmflow.assembly.armv7.psi.ARMv7NumberMixin"
}
