{
    parserClass = "io.github.asmflow.assembly.armv7.parser.ARMv7Parser"
    parserUtilClass = "io.github.asmflow.assembly.armv7.parser.ARMv7ParserUtil"

    extends = "com.intellij.extapi.psi.ASTWrapperPsiElement"

    elementTypeClass = "io.github.asmflow.assembly.armv7.psi.ARMv7ElementType"
    elementTypeHolderClass = "io.github.asmflow.assembly.armv7.psi.ARMv7TokenTypes"

    psiClassPrefix = "ARMv7"
    psiPackage = "io.github.asmflow.assembly.armv7.psi"
    psiImplClassSuffix = "Impl"
    psiImplPackage = "io.github.asmflow.assembly.armv7.psi.impl"

    tokenTypeClass = "io.github.asmflow.assembly.armv7.psi.ARMv7TokenType"

    classHeader = "header.txt"

    tokens = [
        COMMENT = "comment"
        IDENTIFIER = "identifier"
        LINE_FEED = "lf"
        STRING = "string"

        // numbers
        BINARY_NUMBER = "binary number"
        DECIMAL_NUMBER = "decimal number"
        HEXADECIMAL_NUMBER = "hexadecimal number"
        OCTAL_NUMBER = "octal number"

        // registers
        REGISTER = "register"

        // symbols
        BANG = "!"
        COMMA = ","
        COLON = ":"
        DOT = "."
        LBRACKET = "["
        MINUS = "-"
        PLUS = "+"
        POUND = "#"
        RBRACKET = "]"
    ]
}

File ::= Item*
private Item ::= (LabelWithColon | Instruction | Directive) LINE_FEED | LINE_FEED

private Register ::= REGISTER

Directive ::= DOT DirectiveName DirectiveParameters? {
  pin = 2
}
DirectiveName ::= IDENTIFIER
DirectiveParameters ::= DirectiveParameter (COMMA DirectiveParameter)*
DirectiveParameter ::= Label | STRING

Instruction ::= Mnemonic Operands? {
  pin = 1
  mixin = "io.github.asmflow.assembly.armv7.psi.impl.ARMv7InstructionMixinImpl"
  implements = "io.github.asmflow.assembly.armv7.psi.ARMv7InstructionMixin"
}
Operands ::= Operand (COMMA Operand)*
Operand ::= RegisterOperand | Label | Number {
  mixin = "io.github.asmflow.assembly.armv7.psi.impl.ARMv7InstructionOperandMixinImpl"
  implements = "io.github.asmflow.assembly.armv7.psi.ARMv7InstructionOperandMixin"
}

private RegisterOperand ::= RegisterWithShift
  | Postindexed
  | Offset
  | OffsetVariant
  | Preindexed

RegisterWithShift ::= Register (COMMA Shift)?
Shift ::= ShiftType (Number | Register)

Offset ::= LBRACKET Register (COMMA Number)? RBRACKET
OffsetVariant ::= LBRACKET Register COMMA RegisterWithShift RBRACKET BANG?
Preindexed ::= LBRACKET Register COMMA Number RBRACKET BANG
Postindexed ::= LBRACKET Register RBRACKET COMMA Number

Mnemonic ::= IDENTIFIER

ShiftType ::= IDENTIFIER

LabelWithColon ::= Label COLON
Label ::= IDENTIFIER

Sign ::= (PLUS | MINUS)
Number ::= POUND Sign? Based
private Based ::= !<<afterWhitespace>> (BINARY_NUMBER | DECIMAL_NUMBER | HEXADECIMAL_NUMBER | OCTAL_NUMBER)
